- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/models/user.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
- app/views/shared/_navbar.html.erb
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20210426133235_devise_create_users.rb
- db/migrate/20210426152420_add_first_name_and_last_name_to_users.rb
- db/schema.rb
- test/models/user_test.rb
created a User model with the devise
> Authentication

- app/controllers/products_controller.rb
- app/models/product.rb
- app/views/products/index.html.erb
- config/routes.rb
- db/migrate/20210426135322_create_products.rb
- db/migrate/20210426141726_change_staus_in_products.rb
- db/migrate/20210426143733_rename_columns_in_products.rb
- db/migrate/20210426144257_rename_categories_in_products.rb
- db/schema.rb
- test/controllers/products_controller_test.rb
- test/models/product_test.rb
https://user-images.githubusercontent.com/78605007/116122642-5b444880-a6c2-11eb-9be6-a6830a9903af.mov
This is the first version. We will need to make some changes when the map will be added.
> model products, first #index layout"

- app/views/products/index.html.erb
- db/schema.rb
Added one end to the index view
> add an end

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/shared/_form.html.erb
- db/schema.rb
> fixed typo and text align in forms

- app/assets/stylesheets/components/_map.scss
- app/views/products/index.html.erb
- db/schema.rb
> improves display of index

- app/views/products/index.html.erb
- db/schema.rb
Cloudinary works for both the products and the user avatar. will need the index page redesign from @SzczesnaAg to makesure the photos aren't massive.
> cloudinary working for user and other pages

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_searchbar.scss
- app/controllers/products_controller.rb
- app/models/product.rb
- app/views/pages/my_dashboard.html.erb
- app/views/products/index.html.erb
- app/views/shared/_searchbar.html.erb
- db/schema.rb
Some example of searching by: city, category, title.
> basic search

- app/assets/stylesheets/components/_cards.scss
- app/controllers/products_controller.rb
- app/views/products/_info_window.html.erb
- app/views/products/show.html.erb
- app/views/shared/_my_dashboard.html.erb
> img on map, design fixes

- app/assets/stylesheets/components/_faq.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/pages_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/faq.js
- app/views/pages/faq.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
https://user-images.githubusercontent.com/78605007/116606611-45888a80-a931-11eb-8f5e-015a710728cd.mov
I created the first design for faq. Let me know what do you think. We can of course add more questions ;)
> first design for faq

- app/assets/stylesheets/components/_carousel.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pages/my_dashboard.html.erb
- app/views/shared/_my_dashboard.html.erb
> carousel first draft

- app/controllers/application_controller.rb
- app/views/shared/_navbar.html.erb
https://user-images.githubusercontent.com/78602093/116859409-4571de80-ac00-11eb-81f2-6cbcac4aae5b.mov
> adds redirection to viewed page + small navbar changes

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_cards.scss
- app/views/products/show.html.erb
- db/schema.rb
> redesign show page

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/products_controller.rb
- app/views/pages/home.html.erb
- app/views/products/index.html.erb
https://user-images.githubusercontent.com/71139736/116972577-811dae80-acbb-11eb-9212-b045b3e45ac2.mov
I also added the count for puzzles and books the screen recording is in the slack.
> added links to how it works section

- app/assets/stylesheets/components/_card_swap_info.scss
- app/views/shared/_navbar.html.erb
- app/views/swaps/show.html.erb
notification's bell takes the user to the dashboard
> connects bell to the dashboard

- app/views/pages/my_dashboard.html.erb
- app/views/shared/_accepted_swaps.html.erb
- db/schema.rb
> fix on card size in my-dashboard

- app/assets/stylesheets/components/_cards.scss
- app/views/shared/_index.html.erb
> made sure the location and category are aligned on the cards to the bottom and same height for all

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_banner.scss
- app/views/pages/my_dashboard.html.erb
- app/views/shared/_navbar.html.erb
- app/views/swaps/show.html.erb
> dashboard banner responsiveness and avatar white border

- app/views/shared/_searchbar.html.erb
https://user-images.githubusercontent.com/78605007/117154096-d6d98000-adbb-11eb-8764-a8d46c09951c.mov
> no autocomplete in search bar

- app/javascript/channels/swap_channel.js
- app/views/messages/_message.html.erb
- app/views/swaps/show.html.erb
https://user-images.githubusercontent.com/78602093/117186547-3c893480-addb-11eb-9b83-1c153764e861.mov
> fixes the chat display in real time

- app/assets/stylesheets/components/_cards.scss
- app/controllers/application_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/swaps_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/notification_messages.js
- app/policies/swap_policy.rb
- app/views/shared/_accepted_swaps.html.erb
- app/views/shared/_navbar.html.erb
- app/views/swaps/show.html.erb
- config/routes.rb
- db/migrate/20210505081626_add_notification_message_to_messages.rb
- db/schema.rb
Notification for unseen messages
> Notification messages

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_messages.scss
- app/views/swaps/show.html.erb
- db/schema.rb
> chat box width bigger

- app/assets/stylesheets/components/_messages.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/swaps/show.html.erb
> Chatbox is bigger

- app/assets/stylesheets/components/_avatar.scss
- app/controllers/application_controller.rb
- app/views/shared/_accepted_swaps.html.erb
- app/views/shared/_navbar.html.erb
- db/schema.rb
> fixes avatar dropdown list

- app/assets/stylesheets/components/_ikon.scss
- app/assets/stylesheets/components/_reviews.scss
- app/controllers/products_controller.rb
- app/controllers/swaps_controller.rb
- app/views/products/show.html.erb
> rating on show page
